general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display
}

listener {
    timeout = 100                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -05   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 102                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 103                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 104                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 105                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 106                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}
listener {
    timeout = 107                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 108                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 109                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -10   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}

listener {
    timeout = 110                               # 10 min
    on-timeout = hyprctl hyprsunset gamma -15   # set monitor weaker
    on-resume = hyprctl hyprsunset gamma +100   # monitor  restore.
}


#listener {
#    timeout = 10                               # 15 min
#    on-timeout = loginctl lock-session          # lock screen when timeout has passed
#}

#listener {
#    timeout = 3600                              # 1 h
#    on-timeout = systemctl suspend              # suspend pc
#}
